update download cmd

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -7,6 +7,79 @@ set -e
 # clean up leaking environment
 unset GIT_DIR
 
+
+
+s3simple() {
+	local command="$1"
+	local url="$2"
+	local file="${3:--}"
+
+	if [ "${url:0:5}" != "s3://" ]; then
+		echo "Need an s3 url"
+		return 1
+	fi
+	local path="${url:5}"
+
+	if [ -z "${AWS_ACCESS_KEY_ID-}" ]; then
+		echo "Need AWS_ACCESS_KEY_ID to be set"
+		return 1
+	fi
+
+	if [ -z "${AWS_SECRET_ACCESS_KEY-}" ]; then
+		echo "Need AWS_SECRET_ACCESS_KEY to be set"
+		return 1
+	fi
+
+	local method md5 args
+	case "$command" in
+	get)
+		method="GET"
+		md5=""
+		args=(-o "$file")
+		;;
+	head)
+		method="HEAD"
+		md5=""
+		args=(-I)
+		;;
+	put)
+		method="PUT"
+		if [ ! -f "$file" ]; then
+			echo "file not found"
+			exit 1
+		fi
+		md5="$(openssl md5 -binary "$file" | openssl base64)"
+		args=(-T "$file" -H "Content-MD5: $md5")
+		;;
+	*)
+		echo "Unsupported command"
+		return 1
+		;;
+	esac
+
+	local aws_headers=""
+	if [ -n "${AWS_SESSION_TOKEN-}" ]; then
+		args=("${args[@]}" -H "x-amz-security-token: ${AWS_SESSION_TOKEN}")
+		aws_headers="x-amz-security-token:${AWS_SESSION_TOKEN}\n"
+	fi
+
+	local date
+	date="$(date -u '+%a, %e %b %Y %H:%M:%S +0000')"
+
+	local string_to_sign
+	printf -v string_to_sign "%s\n%s\n\n%s\n%b%s" "$method" "$md5" "$date" "$aws_headers" "/$path"
+
+	local signature
+	signature=$(echo -n "$string_to_sign" | openssl sha1 -binary -hmac "${AWS_SECRET_ACCESS_KEY}" | openssl base64)
+
+	local authorization="AWS ${AWS_ACCESS_KEY_ID}:${signature}"
+
+	local bucket="${path%%/*}"
+	local key="${path#*/}"
+
+	curl "${args[@]}" -s -f -H "Date: ${date}" -H "Authorization: ${authorization}" "https://${bucket}.s3.amazonaws.com/${key}"
+}
+
 # LIBREOFFICE_URL="https://appimages.libreitalia.org/portable/LibreOffice-7.3.4.2.basic-x86_64.AppImage"
 
 
@@ -20,11 +93,11 @@ TMP_DIR=$(mktemp -d)
 
 echo "-----> Downloading LibreOffice"
 # curl --silent --show-error --fail -L -o "${TMP_DIR}/${FILE_NAME}" "${LIBREOFFICE_URL}"
-cat ${ENV_DIR}/AWS_S3_ACCESS_KEY
+S3_KEY=$(cat ${ENV_DIR}/AWS_S3_ACCESS_KEY)
+echo $S3_KEY
 
 # aws s3 cp s3://libreoffice7342/LibreOffice-7.3.4.2.basic-x86_64.AppImage "${TMP_DIR}/${FILE_NAME}"
-./download.sh get s3://libreoffice7342/LibreOffice-7.3.4.2.basic-x86_64.AppImage "${TMP_DIR}/${FILE_NAME}"
-
+s3simple get s3://libreoffice7342/LibreOffice-7.3.4.2.basic-x86_64.AppImage "${TMP_DIR}/${FILE_NAME}"
 
 echo "-----> Extracting LibreOffice"
 mkdir -p "${BUILD_DIR}/libreoffice"
